version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules